# Generated by Django 3.2.9 on 2022-02-09 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=20)),
                ('dt_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=100)),
                ('cnh_numero', models.CharField(max_length=30)),
                ('cnh_numregistro', models.CharField(max_length=30)),
                ('cnh_validade', models.DateField()),
                ('cnh_categoria', models.CharField(max_length=5)),
                ('observacao', models.TextField()),
                ('situacao', models.IntegerField()),
                ('cnpj', models.CharField(max_length=15)),
                ('insc_estadual', models.CharField(max_length=20)),
                ('insc_municipal', models.CharField(max_length=20)),
                ('tipo_pessoa', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormPag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=50)),
                ('observacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietario', models.CharField(max_length=255, verbose_name='Proprietário')),
                ('renavam', models.CharField(max_length=100, verbose_name='RENAVAM')),
                ('placa', models.CharField(max_length=8)),
                ('chassi', models.CharField(max_length=35)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('valor_locacao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_aquisicao', models.DateField(blank=True)),
                ('cor', models.CharField(max_length=50)),
                ('numero_portas', models.IntegerField()),
                ('motor', models.IntegerField()),
                ('cambio', models.CharField(max_length=50)),
                ('combustivel', models.CharField(max_length=50)),
                ('nivel_tanque', models.DecimalField(decimal_places=2, max_digits=2)),
                ('km_atual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponibilidade', models.IntegerField()),
                ('observacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora_locacao', models.DateTimeField(auto_now_add=True)),
                ('datahora_prevista_devolucao', models.DateTimeField()),
                ('datahora_devolucao', models.DateTimeField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qtde_dias', models.IntegerField()),
                ('km_devolucao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora_reserva', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.veiculo')),
            ],
        ),
    ]
