# Generated by Django 3.2.9 on 2022-02-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0003_auto_20220209_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='cambio',
            field=models.CharField(max_length=50, verbose_name='Câmbio'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.CharField(max_length=50, verbose_name='Tipo de combustível'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='data_aquisicao',
            field=models.DateField(blank=True, verbose_name='Data de Aquisição do Veículo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='disponibilidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='motor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='nivel_tanque',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Nível do Tanque'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='numero_portas',
            field=models.IntegerField(default=2, verbose_name='Número de Portas'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='valor_locacao',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da Locação'),
        ),
    ]
