# Generated by Django 3.2.9 on 2022-02-09 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0004_auto_20220209_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formpag',
            options={'verbose_name': 'Forma de Pagamento', 'verbose_name_plural': 'Formas de Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='locacao',
            options={'verbose_name': 'Locação', 'verbose_name_plural': 'Locações'},
        ),
        migrations.AlterField(
            model_name='formpag',
            name='forma',
            field=models.CharField(max_length=50, verbose_name='Descrição da Forma de Pag.:'),
        ),
        migrations.AlterField(
            model_name='formpag',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.cliente', verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='datahora_devolucao',
            field=models.DateTimeField(verbose_name='Data / Hora da Devolução'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='datahora_locacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data / Hora da Locação'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='datahora_prevista_devolucao',
            field=models.DateTimeField(verbose_name='Data / Hora prevista p/ Devolução'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='km_devolucao',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Anotação de KM do veículo'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='qtde_dias',
            field=models.IntegerField(verbose_name='Qtde. dias locados'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Total R$'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.veiculo', verbose_name='Veículo'),
        ),
    ]
