# Generated by Django 3.2.9 on 2022-02-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0006_auto_20220210_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locacao',
            options={'verbose_name': 'Locação', 'verbose_name_plural': '4. Locações'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': '5. Reservas'},
        ),
        migrations.AddField(
            model_name='locacao',
            name='valor_previsto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Previsão R$'),
        ),
    ]
