# Generated by Django 3.2.9 on 2022-02-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0007_auto_20220210_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='nivel_tanque',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, verbose_name='Nível do Tanque'),
        ),
    ]
